# Generated by Django 5.1 on 2024-10-27 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id_book', models.AutoField(primary_key=True, serialize=False)),
                ('tieu_de', models.CharField(max_length=200, null=True)),
                ('tac_gia', models.CharField(max_length=200, null=True)),
                ('mo_ta', models.TextField(blank=True)),
                ('noi_dung', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('the_loai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='home.category')),
            ],
        ),
    ]
